spring:
  profiles:
    active: dev
    
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://rm-uf6itdd69r9j2b45ato.mysql.rds.aliyuncs.com:3306/ruoyi-vue-pro?useSSL=false&serverTimezone=Asia/Shanghai&connectionTimeZone=LOCAL
      username: jcs
      password: Jueceshu2021
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        connection-timeout: 20000
    clickhouse:
      jdbc-url: jdbc:clickhouse://106.14.221.209:8123/aikang?compress=0&http_connection_provider=HTTP_URL_CONNECTION
      username: default
      password: 123456
      driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 2
        connection-timeout: 20000
      
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Shanghai
        show_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: org.panjy.servicemetricsplatform.entity
  config-location: classpath:mybatis-config.xml

dashscope:
  apiKey: "sk-4d14608f5c5d40eb926fcd2f44258e20"