# 生产环境配置
spring:
  datasource:
    # ClickHouse数据库连接配置（需要根据实际情况修改）
    url: ${CLICKHOUSE_URL:jdbc:clickhouse://106.14.221.209:8123/aikang?compress=0&http_connection_provider=HTTP_URL_CONNECTION}
    username: ${CLICKHOUSE_USERNAME:default}
    password: ${CLICKHOUSE_PASSWORD:123456}
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Shanghai
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.ClickHouseDialect
    database-platform: org.hibernate.dialect.ClickHouseDialect

# MyBatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: org.panjy.servicemetricsplatform.entity
  config-location: classpath:mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true

# 服务器配置
server:
  port: ${SERVER_PORT:9712}
  servlet:
    context-path: /
  tomcat:
    max-threads: 200
    min-spare-threads: 10
    max-connections: 10000
    accept-count: 100
    connection-timeout: 20000

# 日志配置
logging:
  level:
    root: INFO
    org.panjy.servicemetricsplatform: DEBUG
    org.springframework.web: DEBUG
    org.mybatis: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/service-metrics-platform.log
    max-size: 100MB
    max-history: 30

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  health:
    db:
      enabled: true

# LLM配置
dashscope:
  apiKey: ${DASHSCOPE_API_KEY:sk-4d14608f5c5d40eb926fcd2f44258e20}

# 启用调试模式
debug: true