server:
  port: 8081

spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:clickhouse://106.14.221.209:8123/aikang?compress=0&http_connection_provider=HTTP_URL_CONNECTION
    username: default
    password: 123456
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    type: com.zaxxer.hikari.HikariDataSource

  # 彻底禁用 JPA/Hibernate，不要让 Spring Boot 自动加载
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: org.panjy.servicemetricsplatform.entity
  config-location: classpath:mybatis-config.xml

# 日志配置
logging:
  level:
    root: INFO
    org.panjy.servicemetricsplatform: DEBUG
    org.springframework.web: INFO
    org.mybatis: DEBUG
    com.zaxxer.hikari: WARN
    org.apache: WARN
    org.panjy.servicemetricsplatform.mapper: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
  file:
    name: logs/service-metrics-platform.log
    max-size: 50MB
    max-history: 10
    total-size-cap: 1GB

dashscope:
  apiKey: "sk-4d14608f5c5d40eb926fcd2f44258e20"